#!/bin/sh
#
# builtin-features - Ensure that Octave includes certain important features
# Copyright (C) 2018-2019 Mike Miller <mtmiller@debian.org>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

set -e

OCTAVE=${OCTAVE:-/usr/bin/octave}

octave_cmd="$OCTAVE --silent --no-history --no-init-file --no-window-system"

status=0

$octave_cmd --eval "assert (__have_feature__ ('CURL'))" || status=1
$octave_cmd --eval "assert (__have_feature__ ('FFTW'))" || status=1
$octave_cmd --eval "assert (__have_feature__ ('FLTK'))" || status=1
$octave_cmd --eval "assert (__have_feature__ ('OPENGL'))" || status=1
$octave_cmd --eval "assert (__have_feature__ ('QT'))" || status=1

exit $status
