#!/bin/sh
#
# Copyright (C) 2018 Mike Miller <mtmiller@debian.org>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

set -e

cd $AUTOPKGTEST_TMP

octave="/usr/bin/octave --silent --no-history --no-init-file --no-window-system"

$octave --eval "__run_test_suite__"

cp fntests.log $AUTOPKGTEST_ARTIFACTS

# FIXME: exit status not affected by test failures for now, like 'make check'
